var makeup = "MAC";
console.log("makeup==\"MAC\"? I predict True");
console.log(makeup == "MAC");
console.log("makeup==\"Maybeline\"? I predict False");
console.log(makeup == "Maybeline");
console.log("makeup!=\"Clinique\"? I predict True");
console.log(makeup != "Clinique");
console.log("makeup!=\"MAC\"? I predict False");
console.log(makeup != "MAC");
var Perfumes = "J. Fragrances";
console.log("Perfumes==\"J. Fragrances\"? I predict True");
console.log(Perfumes == "J. Fragrances");
console.log("Perfumes==\"Channel\"? I predict False");
console.log(Perfumes == "Channel");
console.log("Perfumes!=\"Tommy Hilfiger\"? I predict True");
console.log(Perfumes != "Tommy Hilfiger");
var bike = "Honda";
console.log("bike==\"Honda\"? I predict True");
console.log(bike == "Honda");
console.log("bike!=\"Honda\"? I predict False");
console.log(bike != "Honda");
console.log("bike!=\"Suzuki\"? I predict False");
console.log(bike == "Suzuki");
